name: GitHub CI

on:
  push:
    branches:
      - main

jobs:
  sync-code:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Sync code to server directory
        run: |
          echo "Start syncing code to /home/bl/SentryCut"

          rsync -av --delete \
            --exclude ".git" \
            --exclude ".env" \
            --exclude "logs" \
            --exclude "data" \
            --exclude "uploads" \
            ./ /home/bl/SentryCut/

          echo "Code synced successfully"
          ls -la /home/bl/SentryCut