name: Test Local Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Check runner
        run: |
          echo "Runner is working"
          hostname
          whoami
          pwd
          docker version
          docker compose version